name: Deploy to AWS EC2

on:
  push:
    tags:
      - '*'  # Runs only when a tag is created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1b

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_PUBLIC_IP }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Connect to EC2 and deploy code
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          
          # Change directory to your project (or create if not exists)
          PROJECT_DIR=~/flask-project
          if [ ! -d "$PROJECT_DIR" ]; then
            git clone --branch main https://github.com/Karan-skaeo/flask-ci-cd-pythonanywhere.git $PROJECT_DIR
          else
            cd $PROJECT_DIR
            git pull origin main
          fi

          # Navigate to project directory
          cd $PROJECT_DIR

          # Create and activate virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install dependencies
          pip install --upgrade pip
          pip install -r requirements.txt

          # Run Linter
          pip install flake8
          flake8

          # Restart the application (assumes gunicorn is used)
          sudo systemctl restart flask-app

          EOF
